### ISSUE TITLE
Installation fails with Helm 2.16.9: `can't give argument to non-function hasKey .Values "global"`

### ISSUE THREAD

**Issue by AbhyudayaSharma** [StackStorm/stackstorm-ha#136] opened 2020-06-17 12:05 UTC
Hi, I just cloned the repository (cc2697b7f1f550d9e8983f5c922141388472d54b) and ran `helm dependency update` followed by `helm install . --name st2` and the installation fails. Running `helm lint`:

```
sharmaabhyudaya@cloudshell:~/stackstorm-ha$ helm lint
==> Linting .
[ERROR] templates/: render error in "stackstorm-ha/charts/mongodb-replicaset/templates/tests/mongodb-up-test-pod.yaml": template: stackstorm-ha/charts/mongodb-replicaset/templates/_helpers.tpl:84:14: executing "mongodb-replicaset.namespace" at <(hasKey .Values "global") .Values.global.namespaceOverride>: can't give argument to non-function hasKey .Values "global"
```

It looks like a problem with the [mongo-replicaset helm chart](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset) and this particular code path was introduced with https://github.com/helm/charts/pull/21203 . I'm not sure if this is an issue with the Stackstorm helm chart or with Helm or the mongo-replicaset helm chart.

```
$ helm version
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
```

Interestingly, the chart install successfully with Helm v2.16.1. I haven't tried other versions but we can possibly experiment where it all starts falling apart.

**Comment by armab** [comment] 2020-06-17 16:57
Thanks for reporting this!

I'm using Helm `v2.16.7`, so that looks new.
I've checked and the linting issue first appeared when using Helm `v2.16.8`.

**Comment by armab** [comment] 2020-06-17 17:03
Looks like the issue is fixed in a later PR https://github.com/helm/charts/pull/21630, but it adds a warning instead:
```
$ helm lint
2020/06/17 17:57:50 Warning: Merging destination map for chart 'mongodb-replicaset'. The destination item 'global' is a table and ignoring the source 'global' as it has a non-table value of: <nil>
2020/06/17 17:57:50 Warning: Merging destination map for chart 'mongodb-replicaset'. The destination item 'global' is a table and ignoring the source 'global' as it has a non-table value of: <nil>
==> Linting .
Lint OK

1 chart(s) linted, no failures
```

So the solution is to switch to `3.12.0` version of the `mongodb-replicaset` chart before namespace issue was introduced or use the most recent `3.15.1` which includes these Warnings.

**Comment by armab** [comment] 2020-06-17 17:18
I think I'd better go with the `v3.12.0` of mongodb-replicaset chart and we can switch to latest in case of adopting Helm 3 #98.

@AbhyudayaSharma Can you please create a PR to pin the `mongodb-replicaset` version to `v3.12.0`?

**Comment by AbhyudayaSharma** [comment] 2020-06-17 17:19
@armab Sure, I can do that.

**Closed** 2020-06-17 18:25 UTC
Labels: bug
