### ISSUE TITLE
Error: parse error in "stackstorm-ha/templates/_helpers.tpl": template: stackstorm-ha/templates/_helpers.tpl:58: unexpected "=" in operand

### ISSUE THREAD

**Issue by manisha-tanwar** [StackStorm/stackstorm-ha#138] opened 2020-07-02 22:11 UTC
Hi All,

I installed chart using this repo a few times with different scenerios and namespaces. I'm not doing something much different this time but getting error at 👍 
[](https://github.com/StackStorm/stackstorm-ha/blob/master/templates/_helpers.tpl#L60)

```
Installed Helm version v2.10.0
Installed Tiller version v2.10.0
Helm and Tiller are the same version!
Creating tiller namespace (if missing): stackstorm-test
Starting Tiller...
Tiller namespace: stackstorm-test
Running: helm upgrade --install stackstorm-windows-test --namespace stackstorm-test . --timeout 1000

[debug] SERVER: "127.0.0.1:44134"

Release "stackstorm-windows-test" does not exist. Installing it now.
[debug] CHART PATH: /var/lib/go-agent/pipelines/st2-windows-test/st2-helm

Error: parse error in "stackstorm-ha/templates/_helpers.tpl": template: stackstorm-ha/templates/_helpers.tpl:58: unexpected "=" in operand
```

As soon as I change this line from `{{- $values = index $values . }}` to `{{- $values := index $values . }}` It works fine. 
What does this mean?

**Comment by armab** [comment] 2020-07-03 21:13
Duplicate of https://github.com/StackStorm/stackstorm-ha/pull/82

Helm `v2.10.0` was released 2 years ago. We don't support that version.
Please upgrade your Helm to the latest `2.x` branch https://github.com/helm/helm/releases

**Closed by armab** 2020-07-03 21:13 UTC
Labels: invalid

**Comment by manisha-tanwar** [comment] 2020-07-04 00:44
Thanks @armab I tried finding this error but couldn't find so had to open the issue. But yet helm version was causing the probelm and upgrading it to latest version resolved it. Thanks
