### ISSUE TITLE
Stackstorm-ha on Kubernetes with openstack Magnum 

### ISSUE THREAD

**Issue by mpiscaer** [StackStorm/stackstorm-ha#172] opened 2021-01-25 18:20 UTC
Hi,

I try to install Stackstorm-ha on Kubernetes what is running on Openstack Magnum.

When I run the command:
helm install -f stackstorm stackstorm/stackstorm-ha

This fails at creating persistent storages. When I created the storages manual before the deploy it all functional successful.

What is the best way to set the storageClassName to value csi-sc-cinderplugin ?

**Comment by armab** [comment] 2021-01-25 18:59
I believe related issue was asked in the [ StackStorm HA in rancher PV/PVC/Storage Classes #168 ](https://github.com/StackStorm/stackstorm-ha/issues/168).

This applies to K8s cluster configuration itself, rather then Helm chart.

Our recommendation is to configure the https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/ K8s cluster for `Dynamic Volume Provisioning` which is an automatic way to create the persistent volumes based on `PersistentVolumeClaim` storage requests coming from the specific Helm chart configurations (MongoDB and RabbitMQ in our case).

**Comment by cognifloyd** [comment] 2021-07-22 23:55
I think this is very similar to #18 which discusses alternative storage solutions for packs.
My PR in #199 creates a cluster-agnostic way for the chart to handle whatever storage is configured in the cluster. Since there are so many storage solutions out there, this chart really can't manage creating any Persistent Volumes or Persistent Volume Claims (or the other varied storage-related bits).
So, once you have your k8s cluster's storage solution configured, you can add the relevant volume definitions in values (once #199 is merged) to use your storage backend.

I'm closing this as I believe the issue is covered by other issues or PRs. Feel free to reopen if I misunderstood.

**Closed by cognifloyd** 2021-07-22 23:55 UTC
Labels: question
